### ISSUE TITLE
Enable Slurm Accounting Database

### ISSUE THREAD

**Issue by iamh2o** [Daylily-Informatics/daylily#78]
Add mysql setup to the post-install-script (headnode only), connect to this and use it!

Will enable things like limiting inflight jobs to a specific max combined threads/vcpu count.

**Comment by iamh2o** [comment]
# add to post install script
```bash
#!/bin/bash

set -euo pipefail
export DEBIAN_FRONTEND=noninteractive

# Configuration variables
REGION="ap-south-1"
SECRET_NAME="parallelcluster/slurm_mysql_password"
DB_NAME="slurm_acct_db"
DB_USER="slurm"

# Generate secure password
DB_PASS=$(openssl rand -base64 24)

# Install MySQL Server (non-interactive)
apt update -y
apt install mysql-server -y

# Ensure MySQL is running
systemctl enable --now mysql

# Secure MySQL installation non-interactively (set root password and remove insecure defaults)
mysql <<EOF
ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '${DB_PASS}';
DELETE FROM mysql.user WHERE User='';
DROP DATABASE IF EXISTS test;
DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%';
FLUSH PRIVILEGES;
EOF

# Create Slurm database and user
mysql -u root -p"${DB_PASS}" <<MYSQL_SCRIPT
CREATE DATABASE IF NOT EXISTS ${DB_NAME};
CREATE USER '${DB_USER}'@'localhost' IDENTIFIED BY '${DB_PASS}';
GRANT ALL PRIVILEGES ON ${DB_NAME}.* TO '${DB_USER}'@'localhost';
FLUSH PRIVILEGES;
EOF

# Store password securely in AWS Secrets Manager
aws secretsmanager create-secret \
  --name "${SECRET_NAME}" \
  --region "${REGION}" \
  --description "Slurm MySQL DB password" \
  --secret-string "{\"password\":\"${DB_PASS}\"}"


```


# parallel cluster yaml

```yaml
Scheduling:
  Scheduler: slurm
  SlurmSettings:
    Database:
      Uri: "mysql://<HeadNode-IP or hostname>/slurm_acct_db"
      UserName: "slurm"
      PasswordSecretArn: "arn:aws:secretsmanager:<region>:<account-id>:secret:<your-secret>"

```
